"""init

Revision ID: be2e1a06b3ee
Revises: 
Create Date: 2023-03-27 09:15:39.111295

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'be2e1a06b3ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artpost', schema=None) as batch_op:
        batch_op.drop_index('ix_artpost_Title')
        batch_op.drop_index('ix_artpost_enabled')

    op.drop_table('artpost')
    with op.batch_alter_table('artpost2', schema=None) as batch_op:
        batch_op.drop_index('ix_artpost2_author')
        batch_op.drop_index('ix_artpost2_enabled')
        batch_op.drop_index('ix_artpost2_last_updated')
        batch_op.drop_index('ix_artpost2_title')

    op.drop_table('artpost2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artpost2',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('author', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('image_path', sa.VARCHAR(), nullable=True),
    sa.Column('last_updated', sa.VARCHAR(), nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artpost2', schema=None) as batch_op:
        batch_op.create_index('ix_artpost2_title', ['title'], unique=False)
        batch_op.create_index('ix_artpost2_last_updated', ['last_updated'], unique=False)
        batch_op.create_index('ix_artpost2_enabled', ['enabled'], unique=False)
        batch_op.create_index('ix_artpost2_author', ['author'], unique=False)

    op.create_table('artpost',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('Title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('image_path', sa.VARCHAR(), nullable=True),
    sa.Column('last_updated', sa.VARCHAR(), nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artpost', schema=None) as batch_op:
        batch_op.create_index('ix_artpost_enabled', ['enabled'], unique=False)
        batch_op.create_index('ix_artpost_Title', ['Title'], unique=False)

    # ### end Alembic commands ###
